# Generated by Django 2.1.3 on 2018-12-14 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='length',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='length',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='skills.Length'),
        ),
        migrations.AlterField(
            model_name='length',
            name='length',
            field=models.IntegerField(help_text='months'),
        ),
    ]
