# Generated by Django 2.1.3 on 2018-12-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20181215_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecord',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
