# Generated by Django 2.0.9 on 2018-12-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_auto_20181216_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
