# Generated by Django 2.1.3 on 2018-12-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20181213_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrecord',
            name='length',
        ),
        migrations.AlterField(
            model_name='skill',
            name='length',
            field=models.ForeignKey(default='0', help_text='months', on_delete=django.db.models.deletion.CASCADE, to='skills.Length'),
        ),
    ]
