# Generated by Django 2.1.3 on 2018-12-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20181214_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecord',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
