# Generated by Django 2.1.3 on 2018-12-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_remove_jobrecord_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecord',
            name='match',
            field=models.IntegerField(default='1'),
        ),
    ]
