# Generated by Django 2.0.9 on 2018-12-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_jobrecord_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required element.', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='requirements',
            field=models.ManyToManyField(help_text='Select each requirement.', to='skills.Requirement'),
        ),
    ]
